# Choose language and version
language: node_js
node_js:
  - "8"
branches:
  only:
    - master

# Setup custom environment variables
env:
  global:
    - LT_USERNAME=deepakm
    - LT_ACCESS_KEY=gIUJGTZtydrnSbdGro6Hm0yOJDfFBJWGZQ8FdyPA1rv07ZxxQA

# All the step which you want to run in container.
script:
  # Fetching latest code from  git
  - git pull origin master
  # Downloading tunnel binary
  - wget https://s3.amazonaws.com/lambda-tunnel/LT_Linux.zip
  # Extracting tunnel binary
  - sudo apt-get install unzip
  - unzip LT_Linux.zip
  # Executing tunnel binary
  - ./LT -user deepakm@lambdatest.com -key gIUJGTZtydrnSbdGro6Hm0yOJDfFBJWGZQ8FdyPA1rv07ZxxQA &
  - sleep 30
  # Installing dependencies
  - npm install
  # Running test!
  - node_modules/.bin/nightwatch -e chrome